### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#1]
적절히 현실성 있으며, 구현이 단순하진 않은 주제를 선정 한 후
해당 주제를 통해 프레젠테이션을 제작해야 합니다.

**Comment by hhs629629** [comment]
선정된 주제에 적합한 Repository 이름도 결정해야 합니다.

**Comment by DA-EUN00** [comment]
일단 9/7일에 생각한  아이디어는 '성별, 나이, 지역, 선호하는 음식 및 종류, 날씨'를 기반으로 메뉴를 추천해주는 시스템이었습니다.
이것은 학습시킬 데이터를 찾는 것에 어려움이 있다고 지적해주셨어요.

**Comment by DA-EUN00** [comment]
2번째 아이디어는 '알레르기 유발 성분'을 이용해서 데이터를 구분하고, 사용자가 정보 제공을 원하지 않는 성분을 제외하고 그중에서 음식을 제공하는 서비스입니다.
'알레르기 유발 성분'은 프랜차이즈의 경우 홈페이지에서 정보를 제공하기 때문에 크롤링을 통해서 데이터를 모을 수 있습니다.

**Comment by hhs629629** [comment]
'알레르기 유발 성분을 피하는 추천 알고리즘' 이라는 아이디어는 좋지만
대형 프렌차이즈에서 제공하는 메뉴 외에는 데이터를 얻을 수 없어 추천폭이 좁고,
로직이 사용자 입력과 데이터 테이블을 대조하는 단순한 구조이기 때문에
전체적으로 프로젝트의 난이도가 과도하게 낮아질 수 있을 것 같습니다.

**Comment by DA-EUN00** [comment]
어쩌면 첫번째 아이디어가 가능할지도 모르겠어요.
날씨와 음식의 상관관계는 배달음식과 기상을 분석하면 가능해요.
https://dspace.ewha.ac.kr/handle/2015.oak/241476?mode=full

**Comment by hhs629629** [comment]
기상 정보는 기상청등 공공기관에서 제공하는 정보를 통해 얻기 쉬우나
배달 음식의 주문 건수는 카드사 등에서 제공하는 데이터가 대부분이라 저렴하게 얻기 힘든데
배달 관련 데이터중 적절한 데이터를 찾을 수 있을까요?

**Comment by hhs629629** [comment]
기존 아이디어에서 Input을 변경해서 관련성을 입증하기 위한 데이터를 구하기 힘든 "성별/나이/지역/날씨" 등은
배제하고

- 사용자의 선호 음식 종류
- 그 때의 기분에 따라 선택할 수 있는 무언가

를 기준으로 추천을 진행해주면 매번 같은 음식이 나오지 않으면서도
사용자가 해당 서비스와 상호작용 하는 방법에 있어서 다양성을 줄 수 있을것 같습니다
그 무언가로써 일단은 "색"이 적절할 것 같네요
