### ISSUE TITLE
요구사항 분석서

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#10]
요구사항 분석서입니다. 
다이어그램은 아직 첨부하지는 못했고요. 
요구사항 추적표도 아직 수정 전입니다.
[7-요구사항분석서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7242222/7-.zip)

**Comment by hhs629629** [comment]
분석서가 포함해야 하는 다이어그램이 많은것 같은데
시간이 많이 소요 될 것 같으면
일부 저에게 할당 해주시면 됩니다

**Comment by DA-EUN00** [comment]
![UsecCseDiagram](https://user-images.githubusercontent.com/53327279/135311726-2bce0436-c4d7-429b-bce6-a877732728ce.png)
요구사항 분석서에 들어갈 use case diagram입니다.

**Comment by DA-EUN00** [comment]
![인터페이스 분석](https://user-images.githubusercontent.com/53327279/135314984-4a7ccefa-ac80-423c-b18b-f88a2c2d972f.png)
요구사항 분석서에 들어갈 인터페이스 분석입니다.

희상님께서 sequence diagram 맡아주실 수 있으신가요?
제가 내일 저녁 전까지 calss diagram하고 추적표 올리겠습니다.

**Comment by DA-EUN00** [comment]
![ClassDiagram](https://user-images.githubusercontent.com/53327279/135376625-83516988-635d-4106-baf3-6dd8dd532658.png)
요구사항 분석서에 들어갈 클래스 다이어그램입니다.

**Comment by DA-EUN00** [comment]
![ClassDiagram](https://user-images.githubusercontent.com/53327279/135377071-2cbc38a5-5172-4f3a-b8aa-57dd0d9b18af.png)
요구사항 분석서에 들어갈 클래스 다이어그램입니다.
확인부탁드려요.

**Comment by hhs629629** [comment]
![Get_Reccomendation_Food_Sequence](https://user-images.githubusercontent.com/4403080/135446791-d84ba65c-8098-48f6-852a-b27c94f9aab0.png)
![User_Login_Sequence](https://user-images.githubusercontent.com/4403080/135446794-286da355-c9f1-4776-99c1-10a13292003b.png)

로그인, 추천 시퀀스 다이어그램입니다

**Comment by hhs629629** [comment]
Food에 Taste항목은 현실적으로 데이터를 통해 알아내기 힘든 항목일 것 같습니다.
또한 Shape항목은 프로젝트 컨셉에 맞게 Color로 해도 될 것 같네요

**Comment by DA-EUN00** [comment]
[7-요구사항분석서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7259336/7-.zip)
의견주신 대로 고쳤고, 다이어그램도포함 시켰습니다.

**Comment by DA-EUN00** [comment]
의견주신 대로 고쳤고, 다이어그램도포함 시켰습니다
![로그인 시퀀스 다이어그램](https://user-images.githubusercontent.com/53327279/135452778-f46f5bb2-8809-4731-8431-fb9667f5c344.png)
.

**Comment by DA-EUN00** [comment]
의견주신 대로 고쳤고, 다이어그램도포함 시켰습니다.
[7-요구사항분석서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7259360/7-.zip)

**Comment by DA-EUN00** [comment]
[7-요구사항분석서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7326530/7-.zip)
일부 오류를 수정했습니다.

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/137104093-c03bd0d6-a634-491c-aee4-f426d660b98d.png)
'집합' 오타 있습니다

![image](https://user-images.githubusercontent.com/4403080/137104263-957c7a71-06ff-445c-9f3b-d14d0e6f732e.png)
Feeling 부분은 삭제하는 게 좋을 것 같습니다

![image](https://user-images.githubusercontent.com/4403080/137104362-c3a4ed71-2529-4538-b1aa-7a646c500b6c.png)
음식의 '맛', '모양'은 알아내기 힘든 정보입니다 삭제하는 게 좋을 것 같습니다

![image](https://user-images.githubusercontent.com/4403080/137104717-0700430e-f1d9-4e56-a77f-7b127b0da279.png)
감정 분석은 제외해야 합니다

**Comment by DA-EUN00** [comment]
![image](https://user-images.githubusercontent.com/53327279/137160830-584d4b7e-7791-42b0-ab0b-b22729310b0d.png)
이 부분의 감정을 뺐습니다.
[요구사항분석서_빌더.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7339373/_.zip)

해당 내용을 검토해주시면 ecampus의 내용도 수정하겠습니다.
