### ISSUE TITLE
성능 평가

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#11]
저희 서비스의 성능을 검증할 방법을 확립하여야 합니다.

**Comment by hhs629629** [comment]
어떤 관점에서 성능을 따져야 할지 선택해야 하며

우수함을 보여주기 위해선 타 서비스와 비교하는 측면이 필요하지만
차별성이 큰 주제이기 때문에 비교하기 적절한 서비스를 찾아내야 합니다

**Comment by DA-EUN00** [comment]
성능평가를 
1. 사용자 만족도
2. 타 서비스와 비교
이렇게 진행하는거죠?

1. 메뉴선택.dogumaster
http://dogumaster.com/select/menu
- 가장 비슷한 추천 사이트
- 식사유형, 종류, 같이 먹는 사람에 따라 랜덤으로 메뉴 추천

2. 오늘은 뭘 먹을까?
https://kr.shindanmaker.com/359244
- 단순히 랜덤으로 추천

3. 단순한 랜덤  메뉴추천
- 사이트를 특정하기에는 종류가 너무 많음
- 다양한 형태로 존재하나 맞춤 추천이 아닌 단순 랜덤으로 결과를 출력함

제가 위처럼 조사를 좀 했는데 생각보다 메뉴추천 서비스가 좋지 않은 것 같습니다.  
메뉴 추천이 아닌 맛집 추천은 종종 보이기는 합니다.
기존 메뉴추천이 랜덤인 점을 감안한다면 충분히 설득력있는 비교 자료가 나올 것 같습니다.

**Comment by hhs629629** [comment]
차별성 자체는 보여주기 쉽지만
그게 성능적인 면에서 우수한지 검증하는 방법을 선택해야 하는데요
좋은 방법이 떠오르지 않는데 
타 서비스 대비 저희 서비스가 우수하다는걸 보여줄 성능평가 방법이 있을까요?

**Comment by hhs629629** [comment]
어떻게 보여줘도 기존 것보다 부족한 성능이 나오지 않음은 직관적으로 보이는데
발표 분량을 적절히 뽑기에는 뭔가 더 내용이 필요할 것 같네요

**Comment by bytecell** [comment]
카페 Q/A 에서 성능 관련하여 질문이 있었는데, 이에 대한 답변 내용을 참고해보면 좋을 것 같습니다.

**Comment by DA-EUN00** [comment]
카페 Q/A의 내용을 참조했는데요. 
가능할지는 모르겠으나 아직 모델을 정하기 전이니 모델별로 성능평가를 받을 수 있을 것 같습니다.
그리고 만족도에 대한 설문도 진행을 하면 얼추 나올 것 같습니다.

**Comment by hhs629629** [comment]
현재 구현으로는 인공지능을 활용하기에는 힘들것 같아
모델별로 적용할 방법이 있을지 조금 더 고민해볼 필요가 있을 것 같네요
만족도 설문은 좋은데 위의 사이트들에는 평점을 매기는 기능 등이 없어
해당 사이트와 저희 서비스의 차이를 강조하긴 힘들어 보이네요

그래도 서비스 특성 상 사용자에게 만족도 조사를 받는 건 아주 긍정적이라고 봅니다

**Comment by hhs629629** [comment]
저희 서비스의 성능을 평가 할만한 방법을 정리해보면

1. 서비스의 정확도의 평가를 위해 음식 추천을 진행한 후 사용자에게 해당 추천 결과의 만족도를 별점으로 받도록 함
2. 인공지능 모델을 활용하는 계획이 없어 모델 별 성능 평가는 힘들지만, 위 사이트들과 추천까지 걸리는 시간 (서버 응답 시간 등) 의 비교

정도가 떠오르네요
이외에도 위 사이트들을 볼 때 저희의 예상 결과물과 비교하자면

1. 위 사이트들은 선택지의 다양성이 없음, "메뉴 선택.dogumaster"의 경우 식사/요리/간식 이 있는데 식사/요리의 차이점이 뭔지 애매하고([식사|양식|가족]을 해도 스테이크가 나오고, [요리|양식|가족]을 해도 스테이크가 나옴), "오늘은 뭘 먹을까?"는 사용자의 개입이 일체 불가능
2. 위 사이트들은 자신이 먹기 싫은 음식을 설정할 수 없음, 원하는 걸 얻으려면 사용자가 자신이 원하는 음식군이 나올 때까지 계속 추천 요청을 해야 하며, 이는 사실상 응답 시간이 아주 오래 걸리는 서비스를 이용하는 것과 유사한 유저 경험을 제공

이 두 가지는 차별 점으로도 볼 수 있고 한편으로는 성능으로도 볼 수 있어서
서술 방식에 따라 성능으로도 어필할 수 있을 것 같은데 어떻게 생각하시나요?

**Comment by DA-EUN00** [comment]
제가 생각한 걸 구체화 해서 적어주신 느낌입니다. 
정말 깔끔하게 정리해주셨네요. 

제 생각에는 굳이 따진다면 성능이지 않을까 싶습니다.
서비스에서 사람에게 뭔가를 요구한다면 서비스가 안좋다고 느끼니까요.
예를 들어 본인인증을 위해 비밀번호 입력을 반복한다면 그 사이트나 서비스는 사용하지 않는 것처럼
자신이 좋아하는 혹은 원하는 음식군이 나올때까지 계속 결과를 출력한다면 저는 사용하지 않을 것 같습니다.

**Comment by hhs629629** [comment]
성능 평가 계획 발표 자료 입니
다.
[[산학프로젝트][빌더][6주차] 발표자료.pptx](https://github.com/Ind-Univ-Project/Food-Palette/files/7320428/6.pptx)

**Comment by DA-EUN00** [comment]
[3번째 슬라이드]
1. 사용자에게는 0.5단위로 평가를 받고, 평균은 0.1단위로 나타내는 건 어떨까요?
너무 자세한 점수를 요구하는 것은 좋지 않다고 생각합니다.

[4번째 슬라이드]
2. 
![image](https://user-images.githubusercontent.com/53327279/136752335-89c16b26-c024-49e9-aad8-fd6baaa870b5.png)
이 부분을 "제공된 개발자 email등 연락처를 통해 불편사항을 접수하여 제공되고 있는 UI/UX를 지속적으로 평가"로 고치는것이 좋을 것 같습니다.

3. 이 부분도 설문시 평가항목 중 하나로 넣으면 좋을 것 같습니다.

 그외에는 좋습니다.

**Comment by hhs629629** [comment]
1. 별점 그림은 예시일 뿐 실제 구현에서 몇점을 단위로 할지는 저희가 정하면 됩니다
2. 수정완료
 [[산학프로젝트][빌더][6주차] 발표자료.pptx](https://github.com/Ind-Univ-Project/Food-Palette/files/7320558/6.pptx)
3. 설문시 평가 항목 자체를 유저가 자유롭게 작성할 수 있도록 하면 해결될 것 같네요
