### ISSUE TITLE
프로젝트 결과 보고서

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#13]
프로젝트 결과 보고서 초안을 작성해야 합니다.

**Comment by hhs629629** [comment]
https://space.malangmalang.com/open?fileId=m:0:942204329&lang=ko
초안입니다

**Comment by DA-EUN00** [comment]
몇 부분만 수정하면 될 듯합니다.

'결정장애'라는 표현이 부적절하다는 것을 전에 본 적이 있어서 수정하였습니다.
'헤매는'이라는 표현을 쓰셔서 이정표로 바꿨습니다.
![image](https://user-images.githubusercontent.com/53327279/140498096-26e26957-7aca-4f86-8dae-a542adcf215b.png)

그외에도 맞춤법에 맞게 수정했습니다.
[10-프로젝트결과보고서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7482461/10-.zip)

**Comment by DA-EUN00** [comment]
제가 한번 만들어봤는데요. 이상한 점이 있다면 알려주세요
![log in](https://user-images.githubusercontent.com/53327279/140600826-35801131-2e2c-4617-9bd8-444caae0ce0d.png)
![result1](https://us
![foodrecommendation](https://user-images.githubusercontent.com/53327279/140600830-1bf03a02-2425-4dc6-91a4-69d0d9c3007e.png)
![Home](https://user-images.githubusercontent.com/53327279/140600831-3ac41c17-f903-48e7-ba11-e591f3b74e0a.png)
![result2](https://user-images.githubusercontent.com/53327279/140600832-90e18f6a-2bfc-43da-bb82-7803aa3a8bd5.png)
![index](https://user-images.githubusercontent.com/53327279/140600834-524a56f4-e207-46c3-ad38-acf10a1f7167.png)
![result3](https://user-images.githubusercontent.com/53327279/140600835-321f721a-3311-4b6e-a5a1-31231db583de.png)
er-images.githubusercontent.com/53327279/140600828-c2ab1f03-4161-43d5-9827-09732191aa0a.png)
![my page](https://user-images.githubusercontent.com/53327279/140600829-78fcc899-43b6-4059-9261-5f78927120ff.png)

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/140601095-de532e61-f19b-43b4-8d55-cc682998e5d6.png)
이미지 하나가 잘린것 같은데 확인해 보실래요?
개략적으로 구성해도 될 것 같았는데 엄청 자세하게 만들어놔서 충분할 것 같네요

**Comment by DA-EUN00** [comment]
[10-프로젝트결과보고서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7490075/10-.zip)
분량을 맞추느라고 추천 서비스 부분만 사진 넣어놨어요.

**Comment by hhs629629** [comment]
2차 멘토링 이후 수정본 입니다
[10-프로젝트결과보고서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7535453/10-.zip)
