### ISSUE TITLE
이미지 업로드 구조

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#16]
서버에 이미지를 업로드 할 때 필요한 데이터는
1. 이미지의 카테고리
2. 이미지

두 개가 필요합니다.

이것들을 적절히 올릴 규약을 정해야 합니다

현재 떠오른 방법은

1. Multipart를 활용하는 방법
2. JSON을 활용하는 방법

이 있는데 이 둘 중 선호하는 방식을 결정해 주거나
또는 다른 적절한 방법을 제안해 주세요

**Comment by DA-EUN00** [comment]
JSON을 활용하는 방법이 좋을 것 같습니다.

**Comment by hhs629629** [comment]
JSON 양식은 다음과 같이
{
   "category": "비빔밥"
   "image": ~~~~~~
}
으로 하면 될텐데
image의 값은 String이 될텐데
image를 어떤 인코딩 방식을 사용해서 보낼 건가요?

**Comment by DA-EUN00** [comment]
base64를 사용하겠습니다.

**Comment by hhs629629** [comment]
이미지 업로드에 필요한 데이터는 총 3개입니다

1. category : 이미지가 어떤 음식인지 표시합니다 {예) 비빔밥, 타코, 케이크}
2. image_type: 이미지의 파일 유형을 표시합니다 {예) jpg, png, bmp}
3. image_buffer: base64로 인코딩된 이미지 파일입니다

위 3개의 값을 포함하여 JSON 양식으로
http://addr.of.server/upload_image 에 Post방식으로 전달하면

response로 해당 이미지가 서버에 저장된 이름 (*uuid를 사용)을 반환합니다
