### ISSUE TITLE
Food Palette의 홈페이지 munu

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#23]
제가 일단 menu를 아래 사진처럼 구성을 했는데요.
혹시 추가해야되는 내용이 있을까요?
![image](https://user-images.githubusercontent.com/53327279/143187580-542b1614-38da-464b-acf9-712954eb5e10.png)

https://github.com/Ind-Univ-Project/Food-Palette/blob/69d468ab581ff3840fe6760533a2cfeb60d5ca4c/front_end/main.html

**Comment by rajpatel1092005** [comment]
contact info

**Comment by hhs629629** [comment]
이미지 업로드 기능이 빠져있는것 같네요

**Comment by DA-EUN00** [comment]
이미지 업로드 기능은 Mypage에서 가능하게 할 생각입니다.
