### ISSUE TITLE
Food Palette의 이미지 불러오기

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#28]
1. 음식 추천 결과에서 이미지 불러오기
2. 사용자가 업로드한 이미지 불러오기

이렇게 2부분에서 이미지를 불러와야하는데요.
어떻게 하는지 아실까요?

**Comment by hhs629629** [comment]
현재 API 구성에 의하면

사용자가 이미지를 업로드 할 때는 서버의
http://address.of.server/upload_image 에 Post방식으로
Request: JSON { category: "볶음밥", image_type: "png", image_buffer: "SU1BR0UgU1RSSU5HIElOVE8gQkFTRTY0....."}
를 보내면 Response로 
해당 동작이 성공 시
Status: OK / body: 서버에서 해당 이미지가 저장된 이름
을 전달합니다

2번의 경우 이 때 받은 이미지의 이름을 UserDB에 저장하고 있다가
서버에 해당 이름으로 이미지를 요청하면 얻을 수 있고

1번의 경우 음식 추천 결과로 JSON을 이미지 이름 리스트를 반환할 것입니다
이 리스트의 각각의 이미지 이름들로 서버에 요청하면 이미지를 얻을 수 있습니다

서버에 이미지 이름으로 이미지를 요청하는 방법은
http://address.of.server/image/image_name 에 Get방식으로 요청을 할 경우
이미지를얻을 수 있습니다

이미지의 이름은 uuid를 사용할 예정이므로
UserDB에서 이미지의 이름을 저장하고 있을 column은 최소 CHAR(36)이상의 크기를 줘야 할것입니다

**Comment by DA-EUN00** [comment]
감사합니다. 한번 해보겠습니다.
