### ISSUE TITLE
추천 Request 양식

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#31]
추천 Request는 다음과 같은 정보를 포함하여야 합니다

1. 색깔 리스트: 유저가 선택한 색깔들의 리스트
2. 유저가 최근에 먹은 음식 + 유저가 싫어하는 음식 리스트:  이미지를 업로드 할 당시의 category와 대응되는 값으로 해당 리스트를 기반으로 추천을 필터링 합니다

2번의 경우 category는 이견 없이 String으로 전송하면 됩니다
그러나 1번의 경우 색깔의 리스트이기 때문에 어떤 방식으로 전송할지 결정해야 합니다

예시를 들어보자면

 Hex Code의 리스트
`[ "#FBC064", "#AA6600", "#CA5400", ....]`

 RGB의 리스트
`[
   {
      r: 165,
      g: 44,
      b: 33
   },
   {
      r: 100,
      g: 33,
      b: 16,
   },
 ....
]`
등등 다양한 방법 중에서 편한걸로 선택하시면 됩니다

**Comment by DA-EUN00** [comment]
일단 제가 아래에 보이는 것처럼 해놨거든요.
만약에 이대로 간다면 string 형태로 전송할 것 같습니다. 

https://github.com/Ind-Univ-Project/Food-Palette/blob/951ea3561966567f64c551e1d0e72e8060c90590/front_end/MenuRecommendation.html

![image](https://user-images.githubusercontent.com/53327279/143676951-49b34e75-fe73-4174-b1e4-c28aaa96f643.png)

**Comment by hhs629629** [comment]
색을 String으로 전달하는건 적절하지 않습니다
일단 저기에 있는 색들이 사진에 있는 색을 전부 커버하지 못할 것 같고요
각 색이 포함하는 범위가 애매합니다

사진에는 저기 써둔 색들 말고도 다양한 색이 나오는데
그걸 저기있는 색들로만 구분하려면 문제가 생길것입니다

**Comment by DA-EUN00** [comment]
사용자에게 많은 선택권을 주는 건 오히려 혼란스럽게 할 수 있을 것 같아요.
색에 따라서 범위를 정하면 될 것 같고요.
음식을 관찰해보니 많은 색이 필요하지 않더라고요. 
요구사항 정의서에도 색을 10가지로 받기로 적었는데, 제가 9개만 올려놓았네요.
한가지 색만 추가하면 될 것 같습니다.

**Comment by DA-EUN00** [comment]
분홍색을 추가했습니다.
빨강색, 주황색, 노란색, 초록색, 파랑색, 보라색, 검정색, 갈색, 흰색, 분홍색입니다.

https://github.com/Ind-Univ-Project/Food-Palette/blob/7d8f1a0e506318af24d5dbfd69c5808999bd0867/front_end/MenuRecommendation.html

**Comment by hhs629629** [comment]
선택권을 제한하되 색의 범위를 늘리면 됩니다
전체 색이 만약에 1000개가 있더라도
한번에 사용자에게 보여주는건 그중 랜덤 10개만 선정해서 보여주면
사용자가 많은 선택지 속에서 고민할 필요가 없죠

그렇지만 음식을 분석해본 결과 10가지 색으로는 여러가지 문제가 생깁니다
1. 음식 사진을 처리할 때 처리 비용이 높아집니다
2. 각 색이 차지하는 범위가 상이해 추천 결과가 이해가 안되는 형태로 나올 확률이 매우 높아집니다
3. 제가 몇가지 음식 사진을 분석해본 결과 저 10색에 포함되지 않아 보이는 사진이 많이 나왔습니다 오히려 저런 원색계열 색은 음식에 포함되지 않을 확률이 높아서 질감 차이가 크게 느껴집니다

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/143678844-94056090-9a3e-4b05-a45f-9970ba6e5692.png)
색 영역은 RGB로 표현할 때 다음과 같이 (R,G,B)를 각 축으로 하는 3차원 영역으로 생각할 수 있습니다
이 때 웹에서 사용하는 Color code에 맞추면
전체 색은 R,G,B 각 각 0~255영역 사이에 정의되는 형태인데

이 3차원 영역을 사용자에게 그럴듯하게 보이게 10개의 공간으로 분할해야 합니다
그나마 R,G,B, 검정, 흰색만으로 구성되면 간단하나
Red = (255, 0, 0)
Yellow = (255, 212, 0)
Orange = (255, 127, 0)
Brown = (150, 75, 0)
Purple = (128, 0, 128)
이렇게 애매한 위치에 있는 색들이 전체 색 영역을 적절히 나누기는 힘들것입니다

**Comment by DA-EUN00** [comment]
Red = (255, 0, 0) ~ (255, 63, 0)
Yellow =(255, 170, 0)~ (255, 212, 0)
Orange = (255, 64, 0)~(255, 169, 0)
이런식으로 범위를 지정해도 안되는 건가요?
10개의 범위로 나눴을 때 그 영역들이 모두 같을 필요는 없으니까요.

**Comment by hhs629629** [comment]
그러면 (255,64,1) 이 나오면 또 얘기가 어려워지는 데다가
단순히 수치적으로 나눴을때 사용자가 그 범위 내의 색을 정말 같은 색으로 인지하냐의 문제가 여전히 존재합니다

**Comment by hhs629629** [comment]
예를들어 이 색은
![image](https://user-images.githubusercontent.com/4403080/143681191-da0d80c0-dce4-4766-a7d5-0ad1303a2194.png)

 (0,255, 254)로 저 구분 대로라면 파란색(0, 0, 255)보다는 초록색(0, 255, 0)에 가까운 색입니다
과연 이 색이 나오면 초록색이라는 점에 사용자가 공감하기 쉬울까요


더 나아가서 이 색은
![image](https://user-images.githubusercontent.com/4403080/143681204-dc5358c4-e226-4e7a-acb9-557948307253.png)

(0, 254, 255)로 위 색과 다르게 파란색입니다
위에건 초록이고 아래건 파랑이라는 점에 있어서 사용자의 공감대를 얻기는 힘들거라고 봅니다

**Comment by DA-EUN00** [comment]
물론 범위를 지정을 하면 보는 사람에 따라 어떻게 구분은 할지는 달라집니다.
그렇다고 해서 사용자에게 255*255*255개 만큼의 입력을 받을 수도 없고
이 중에서 10개를 랜덤으로 보여준다고 한다면 각 색이 비슷할 수도 있을 것입니다.
(예를 들어 초록, 청록, 민트, 파랑, 녹색과 같이 비슷한 계열들로요.)
그렇다면 최대한 색들의 범주가 겹치지 않게 해서 제공을 할텐데 이럴 경우 10개의 범위로 나눠서 제공하는 것과 무엇이 다른것인지 모르겠습니다.
앞서 예로 들어주신  (0,255, 254)와 (0, 254, 255)는 범위의 문제라고 생각을 합니다.
이는 범위를 다시 정하면되는 일입니다. 예시로 들어주신 문제가 없는 것은 아니나 이렇게 된다면 색의 수는 더 많아질 것이고 사용자의 선택이 더 어려워질 수 있습니다.
음식을 추천해주는 우리 서비스가 색을 선택하는데 어려움을 겪어서 사용하지 못하게 된다면 이는 큰일이 아닐 수 없습니다.

**Comment by hhs629629** [comment]
제가 사진들로 테스트 해본 결과
4 * 4 * 4 색 정도 제공하면 해당 색 범주 안의 경우엔 어느정도 유사성을 느낄 정도가 됐습니다
그럼에도 각 색이 비슷하기 보다는 확실히 다르다는 게 느껴질 정도도 되고요

예를들어 위 커멘트에서 보여준 색은 파랑, 초록 어느 범주에 넣더라도 그다지 비슷하다고 느껴지지도 않을 색입니다
그렇다고 위 색을 저희가 어느 범주로 설정하더라도 그건
개발자의 주관이 심하게 포함되었기 때문에 조금 다른 관점을 가진 사용자는 공감하기 힘들 수 있습니다

그에 비해 R G B 각각을 4등분 해서 활용하면
객관적으로, 수치적으로 비슷한 색끼리 묶이기 때문에 개발자의 주관 문제에서 자유로울 수 있습니다
위 두 색은 객관적으로 봐도 충분히 구분이 안될정도로 비슷합니다

그렇지만 위 두 색은 어딜 보더라도 파랑, 초록이랑 비슷하지는 않습니다

이런걸 객관적으로 반영하려면 영역 분할도 개발자의 주관에 따라 달라질 수 있는 방법을 활용해선 안될거라고 봅니다

**Comment by hhs629629** [comment]
256을 4로 나누면
64의 값이 나옵니다
예를들어 R값이 64가 차이난다면 충분히 다르게 느껴지겠죠
![image](https://user-images.githubusercontent.com/4403080/143768677-2a33061b-8f90-4105-942c-63baf0368869.png)
![image](https://user-images.githubusercontent.com/4403080/143768692-df14b6ea-dcee-45e8-8b92-b4b379a399fd.png)
위 예시는 (255, 0, 0) 과 (191, 0, 0)입니다 색에 민감하지 않은 사람이라도 차이를 느낄 정도는 될 것 같고요
(모니터 색 표현력에 따라 차이가 있을 수 있습니다)

그렇기 때문에 각 영역의 범주는 64면 충분합니다

그렇지만 각 영역의 대표색은 해당 영역의 중간값으로 하면 됩니다
즉 영역의 양끝점과 32의 거리를 가지는 색, 해당 영역의 중간의 색으로 하면 됩니다
![image](https://user-images.githubusercontent.com/4403080/143768747-7024559f-6566-4f5f-8201-ae437cb4e9cc.png)
![image](https://user-images.githubusercontent.com/4403080/143768738-8665dce3-a592-4a6b-ac39-f84804e805a3.png)
![image](https://user-images.githubusercontent.com/4403080/143768801-7b847cdb-c748-48f7-b4ef-a095ce5b65fd.png)

위 예시는 (255, 0, 0)과 그와 32차이나는 (223, 0, 0) 그리고 그와 또 31 차이나는 (192, 0, 0) 입니다
맨 위에걸 보고 중간 거를 보거나, 중간걸 보고 그 아래걸 보면 그 차이가 크게 티나지 않는 수준임을 알 수 있습니다

저희가 유저에게 제공하는 색은 저 각 영역의 중간값인 대표색을 제공하면 됩니다
유저는 각 영역의 양 극단을 볼 수 없습니다, 자신이 선택한 대표색과, 추천으로 나온 음식의 색을 볼 수 있을 뿐이죠

즉 유저는 맨 위에 색과 맨 아래색을 비교하지 않습니다
맨 위에 색과 중간색 또는 맨 아래 색과 중간 색을 비교를 해보겠죠

그렇지만 10가지 색 분류 방법을 적용하면 당연하게도
![image](https://user-images.githubusercontent.com/4403080/143768991-8574debd-dee7-4222-bfe8-5689679e8a5c.png)
![image](https://user-images.githubusercontent.com/4403080/143768998-92cc1b73-e717-459e-9f39-4010b45126b1.png)
(0, 0, 255) 와 (0, 255, 255) 를 비교해 보고서는
내가 고른 색이 음식 색에 정밀하게 반영되지 않았다는 것을 느끼고 실망할 것입니다

**Comment by DA-EUN00** [comment]
정밀하게 반영이 안되는 것은 맞는 말씀이십니다.
저희가 디자인을 위한 색상표를 만드는게 아니잖아요?
음식 추천을 위한 색상을 정하는 것인데  64가지나 되는 색을 추천을 받아야할지 잘 모르겠습니다.
64가지는 너무 많다고 생각이 됩니다.
가령 5점 만점의 별점을 주는 것도 그 가짓수가 많아서 Good or Bad로 평가하는 것을 고려해보라고 다른 팀에게 코멘트 해주신 적이 있습니다.
따라서 저는 10가지라는 선택지도 많을 수 있으나 음식을 관찰했을 때 적어도 10가지는 들어가야 되지 않을까 했던 겁니다.

**Comment by hhs629629** [comment]
64가지를 전부다 보여주라는게 아닙니다
전부다 보여주면 당연히 가짓수가 많아서 사용자가 혼란을 겪을 것이 분명합니다

저 중에 10개의 색을 선택해서 보여주면 됩니다
그러면 사용자가 고민을 하게 될 일은 없습니다

그렇지만 그 10개의 색을 선택하는 과정이 개발자의 주관에 근거한 방법이 아닌
수치적이고 객관적인 방식으로 선택되어 사용자가 선택한 색과 추천을 통해 나온 결과물 사이의 괴리를 느끼지 않도록 하는게 중요하다는 겁니다

그러면 정밀하게 반영 되지 않는 문제도 해결되고
사용자가 선택을 주저하게 될 일도 없습니다
또한 꼭 10개가 아니라 9개 16개 등 디자인 적으로 더 적절하게 보일 가능성도 생깁니다
10개가 많다면 9개 3 * 3 으로 표현해서 주면 사용자가 보기에도 더 정돈 되어 보일것입니다

**Comment by hhs629629** [comment]
그 외에도 색을 10가지로 선택하여 String을 통해 전달하는 방식은
소프트웨어 공학적으로 상당히 안좋습니다

예를들어 기존 사용자들은 Blue (0, 0, 255) / Aqua(0, 255, 255) 를 구분 못할거라는 가정 하에
색 영역을 나눠 놓았다고 가정해봅시다 (즉 Aqua는 Blue에 포함됩니다)

그러나 예상 외로 사용자들의 색 구분 능력은 민감했고
그 결과 Aqua는 Blue와는 다른 색으로 보여줘야 했고

사용자에게 제공되는 색에 Aqua가 추가 되게 됩니다
그러면 단순히 Aqua를 전송하는 로직 하나를 추가 하게 되는게 아니라
Aqua의 범위를 어디로 설정할지, 기존에 존재하던 색의 영역을 얼마나 줄이고 Aqua에 할당할지 논의를 해야 하고
해당 색 영역이 차지하는 범위를 찾는 코드를 새로 코딩해야 합니다

이 과정에서 일반적으로 if-else 또는 switch-case 형태의 구문을 사용하게 되는데
물론 위 구문들은 여러가지 생성 패턴을 사용해서 OCP 친화적으로 사용할 수 있으나
그럼에도 완전히 if-else, switch-case 구조를 삭제할 수 있는 형태가 아니기 때문에
변경에서 자유롭지 못합니다

또한 각 색 영역을 수치적으로 나누는게 아니기 때문에 변경 과정에서 오류가 발생할 확률이 매우 높고
경계값이 매우 많아지고 복잡한 구조를 띔에 따라 테스트 용이성이 매우 낮게 구성될 것입니다
또한 새로운 경계를 추가하는데 있어 테스트의 변경도 아주 복잡한 형태로 이루어질 것입니다

그에비해 수치적으로 영역을 나눈 방식을 사용하면
단순히 기존 알고리즘에서 일부 수치를 변경하는 것에 그칠것입니다

**Comment by DA-EUN00** [comment]
네 그러면 어떻게 수정하기를 원하신가요?

**Comment by DA-EUN00** [comment]
12/3일까지 마감이기 때문에 최소한으로 수정했으면 합니다.

**Comment by hhs629629** [comment]
전체 색을 64색으로 나누고
각 영역의 중간값을 본인이 원하는 개수 (9개, 10개, n개) 만큼 랜덤하게 사용자에게 제시해주면 됩니다

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/143771551-82151522-8754-40ff-a39a-4d059ad4ebd0.png)
수업 자료에 의하면 마감은 14주차 토요일로
산학프로젝트 수업의 14주차 토요일은 12/11 입니다

**Comment by DA-EUN00** [comment]
9개, 16개, 25개,...,64개까지 하실 생각이신가요?

**Comment by DA-EUN00** [comment]
64= (2^2)^3 이니까
4, 8, 64 이렇게 제공을 해도 될 것 같고요.
상대적으로 적색계열에 비해서 청색 계열의 비율이 음식에서 적으니까 적색 계열을  몇 개 더 추가를 해도 되고요.

**Comment by DA-EUN00** [comment]
각 색의 RGB값을 구해주실 수 있나요?

**Comment by hhs629629** [comment]
총 255까지의 값을 가지는 각 색에서
4등분을 하였으니
0 ~ 63 / 
64 ~ 127 / 
128 ~ 193 /
 194 ~ 255 네 구역으로 나옵니다
0 ~ 63 중간값은 31 / 64 ~ 127의 중간값은 75 등등을 조합해서 각 색을 구성하면 됩니다

**Comment by DA-EUN00** [comment]
제 참고해서 색을 구성하겠습니다.
