### ISSUE TITLE
이미지 업로드 base관련 문제

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#38]
제가 이미지 업로드 하는 부분을 수정중입니다.
현재 업로드할 경우 아럐와 같은 화면을 확인할 수 있습니다. 해당 문제를 어떻게 해결하면 좋을까요?

![image](https://user-images.githubusercontent.com/53327279/143766072-163077b9-2c9f-4bff-90be-2f4a077c5ff6.png)

https://github.com/Ind-Univ-Project/Food-Palette/blob/6914ed4453957c18c63d0feec9f4ba1aab740e82/front_end/src/ajax.js

![image](https://user-images.githubusercontent.com/53327279/143766032-776d655e-a3d6-4e61-a67b-93eeb4b9636d.png)

**Comment by DA-EUN00** [comment]
https://github.com/Ind-Univ-Project/Food-Palette/issues/16

해당 이슈를 참고해서 수정중입니다.

**Comment by hhs629629** [comment]
Content-Type은 multipart/form-data가 아닌
application/json 이여야 합니다

**Comment by DA-EUN00** [comment]
![image](https://user-images.githubusercontent.com/53327279/143768970-7339a736-bf1f-4493-b94d-d5bdda91a719.png)
https://github.com/Ind-Univ-Project/Food-Palette/blob/4a846d13aedc4ce4400ad40a88dab161ffc23ea5/front_end/src/ajax.js
이렇게 바꿨는데 안되요....

**Comment by hhs629629** [comment]
어떤 메세지가 뜨면서 실패하나요
위와 같나요?

**Comment by DA-EUN00** [comment]
네. 같아요....

**Comment by hhs629629** [comment]
제가 ajax가 case sensitive 한지는 모르겠는데
contentType이라고 써보고
dataType도 json으로 지정해보는건 어떨까요

**Comment by DA-EUN00** [comment]
네 타입 바꿔서 해결했습니다.
