### ISSUE TITLE
이미지 GET 404오류

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#42]
404에러가 뜨는데 뭐가 문제인지 아신가요?
제 생각에는 url 문제인 것 같아요.

![image](https://user-images.githubusercontent.com/53327279/143770592-1c31aeec-5be4-4707-8b8b-11f72d2d629f.png)
https://github.com/Ind-Univ-Project/Food-Palette/blob/9a4ad98f5fce68fe7a4cd7012a7d961cdca53f22/front_end/src/F-RResult.js

**Comment by hhs629629** [comment]
image를 get 하려면 image_name에 적절한 이미지 이름을 써넣어야 하는데
그 이 전에 뭔가의 이미지를 업로드 했어야 얻을 수가 있을겁니다

올린 이미지 이름이 뭔가요?

**Comment by DA-EUN00** [comment]
아직 post를 성공하지 못했기 때문에 성공하지 못했습니다.
하지만 사용자가 post를 하지 않아도 서버에 있는 추천 사진이 떠야하는데 어떻게 하죠?

**Comment by hhs629629** [comment]
현재는 테스트 용으로 한개의 이미지를 업로드 해놓았습니다
d9562bca-afe0-4f9a-8587-f17cd9b54e0f.png
이 이름으로 접근하면 확인해볼 수 있습니다
