### ISSUE TITLE
이미지 GET 200 오류

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#43]
400에러가 아닌 200에러가 납니다.
![image](https://user-images.githubusercontent.com/53327279/143771495-abc83176-ae5d-4446-ac80-75385b62454f.png)

![image](https://user-images.githubusercontent.com/53327279/143771553-ddd1c1c8-5526-416a-9209-9533bd2b14a1.png)
이렇게 하는게 맞을까요?

다음은 400에러 관련 이슈입니다.
https://github.com/Ind-Univ-Project/Food-Palette/issues/42

**Comment by hhs629629** [comment]
https://developer.mozilla.org/ko/docs/Web/HTTP/Status/200

200은 오류가 아니라 성공입니다

**Comment by DA-EUN00** [comment]
성공인데 net::ERR_FAILED 200 이렇게 떠서요.

**Comment by hhs629629** [comment]
데이터가 이미지인데 json으로 받으려고 해서 그런것 같습니다

**Comment by DA-EUN00** [comment]
GET으로 받아오는 데이터의 형태가 구체적으로 어떤 형식인지 알 수 있을까요?
POST를 할 때, {category: '', image ...} 이런 형식으로 넘겨서 GET도 동일한 형식의 json일 줄 알았습니다.

**Comment by hhs629629** [comment]
그냥 이미지 입니다
웹 브라우저 주소창에 저 데이터 넣어보면 이미지를 볼 수 있을겁니다

**Comment by DA-EUN00** [comment]
그럼 데이터가 이미지라고 하셨는데, `이미지이름.png`와  같은 형식으로 넘어오는 건가요?

**Comment by hhs629629** [comment]
이미지가 말 그대로 이미지 그 자체입니다
HTTP 패킷으로
헤더에는 Content-Type: image/? (?는 이미지 파일에 따라 jpeg, png, bmp 등..)
body에는 이미지 파일 바이너리가 채워져서 넘어옵니다

즉 해당 주소를 

`<img src="http://1.246.129.141/image/d9562bca-afe0-4f9a-8587-f17cd9b54e0f.png">` 

이런식으로 활용하면 페이지에 표시되게 할 수 있습니다

당장 깃허브에 저 코드를 그대로 써넣어도
<img src="http://1.246.129.141/image/d9562bca-afe0-4f9a-8587-f17cd9b54e0f.png">
표시되는걸 볼 수 있습니다

**Comment by DA-EUN00** [comment]
데이터 타입에 뭘 적으면 되나요?
![image](https://user-images.githubusercontent.com/53327279/143773092-513cd5a1-60f7-4fd6-9ad6-33dfc24e514c.png)
https://github.com/Ind-Univ-Project/Food-Palette/blob/f320b698d795d5745483b867f00409fba01fbb73/front_end/src/F-RResult.js

**Comment by hhs629629** [comment]
image/? 입니다
이 ? 는 요청하는 경로를 활용하여 알아낼 수 있습니다
예를들어 위의 요청경로의 .png를 통해 해당 데이터 타입은
image/png 로 요청하면 됩니다

**Comment by DA-EUN00** [comment]
말씀해주신대로 고쳤는데 안되요ㅠㅠㅠㅠㅠ

![image](https://user-images.githubusercontent.com/53327279/143773625-20a83454-af56-4de9-b218-619c8da44355.png)

**Comment by hhs629629** [comment]
어느 라인에서 나는 에러인지 중단점을 걸어서 테스트를 해볼 필요가 있을 것 같습니다

**Comment by hhs629629** [comment]
ajax 자체가 크로스도메인을 보안상 허용하지 않네요
https://m.blog.naver.com/youngram2/220129424078

**Comment by DA-EUN00** [comment]
알려주신거를 읽었는데요. 
Proxy 서버를 두는 방법이 제일 적합한 것 같아요.
이 방법은 중간에 Proxy 서버를 두는 것인데 서버 설정을 하는 것을 추천을 해주셔서요.
그 외에도 서버를 설정해야한다고 하는데요.

찾아보니까 Accss-Control-allow-origin 설정을 바꾸면 된다고 하네요.

혹시 가능하신가요?

**Comment by hhs629629** [comment]
그 이전에 어떤 목적으로 ajax를 통해서 이미지에 접근하려는건지 알 수 있을까요?

**Comment by DA-EUN00** [comment]
이렇게 바꾸니까
![image](https://user-images.githubusercontent.com/53327279/143775306-5e2791db-80fc-4921-b5ec-c0750a98c866.png)
에러메시지도 바뀌네요. 'image/png'이 실행이 불가능하다네요?
![image](https://user-images.githubusercontent.com/53327279/143775294-7ad3e809-0efc-4e35-b347-8a93aca39839.png)
