### ISSUE TITLE
결과 출력하는 부분의 데이터 전송 방법

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#44]
추천 받은 음식의 이름과 사진은 어떻게 전송되나요?

**Comment by DA-EUN00** [comment]
https://github.com/Ind-Univ-Project/Food-Palette/issues/28
해당 이슈를 읽었으나 이해가 되지 않아 추가적으로 여쭤봅니다.

**Comment by hhs629629** [comment]
추천 부분은 아직
Request를 어떤식으로 보낼 지 정해진게 없어서 구상만 하고 있지만
아마 이미지의 이름들을 json 형식의 리스트로 보내게 될 것입니다

[ "74c46616-1649-49a2-b849-9ec271d32714.png", "d9562bca-afe0-4f9a-8587-f17cd9b54e0f.png", .....]
이런식으로 추천 결과 목록을 반환할 겁니다
그러면 웹 서버 측에서는 해당 이름들을 기반으로 이미지를 참조하면 됩니다

**Comment by DA-EUN00** [comment]
그럼 Get으로 json형식의 이미지 목록을 받으면
서버주소+이미지.png로 참조하면 된다는 말씀이시죠?

**Comment by DA-EUN00** [comment]
그럼 
[result1의 이름, result1.png, result2의 이름, result2.png, result3의 이름, result3.png, ...]
이런식으로 리스트가 구성되나요?

**Comment by hhs629629** [comment]
대략
`[
   {
      category: "붕어빵",
      path: "74c46616-1649-49a2-b849-9ec271d32714.png"
   }
   {
      category: ....,
      path: ......
   }
]`
이런 양식일 것 같네요

**Comment by DA-EUN00** [comment]
넵 감사합니다.
