### ISSUE TITLE
GET시, CORS 정책 해결 방법

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#50]
GET을 할 때, CORS 정책 때문에 에러가 발생합니다. 
이전에도 비슷한 문제가 있었는데 해결을 못했었거든요...
이거 어떻게 하죠?
![image](https://user-images.githubusercontent.com/53327279/144870942-0d9d3880-2dda-4308-bf2c-f7b9de0cb19b.png)
![image](https://user-images.githubusercontent.com/53327279/144871069-4da57fa3-069d-480f-bcac-ec728bd19469.png)

**Comment by hhs629629** [comment]
ajax를 안쓰는 방식을 택하는게 좋을 것 같습니다

**Comment by DA-EUN00** [comment]
그럼 http로 해보겠습니다.

**Comment by hhs629629** [comment]
http://superkts.pe.kr/helper/view.php?seq=V&seq=141
https://kkk-kkk.tistory.com/m/entry/%EC%98%88%EC%A0%9C-9-15-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EA%B0%A4%EB%9F%AC%EB%A6%AC-%EB%A7%8C%EB%93%A4%EA%B8%B0-new-Image%EB%A1%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EB%A1%9C%EB%94%A9
https://solbel.tistory.com/m/85
https://ddorang-d.tistory.com/6

동적으로 태그를 생성하고 이미지를 불러오는건 다양한 방법이 있는것 같네요
참고해서 해보세요

**Comment by hhs629629** [comment]
CORS 로 실패한 리퀘스트는 위쪽의 저 코드랑 관련이 없는 것 같습니다

**Comment by DA-EUN00** [comment]
GET으로는 이미지가 아니라 #44 부분처럼
[ { category: "붕어빵", path: "74c46616-1649-49a2-b849-9ec271d32714.png" } { category: ...., path: ...... } ]
해당 부분을 받아오기 위함입니다. 

CORS부분은 더 찾아보겠습니다.

**Comment by hhs629629** [comment]
일단 서버가 CORS는 허용을 해놓았습니다
이 상황에서 추가적으로 CORS로 문제가 되면
좀더 세밀한 디버깅이 필요할 것 같네요

**Comment by DA-EUN00** [comment]
관련 문제는 사라졌네요. 감사합니다.
