### ISSUE TITLE
색 고르는 화면

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#56]
색 고르는 화면을 아래와 같이 작성해봤습니다.
색 구성이 마음에 안들으시면 알려주세요. 해당 색으로 바꾸겠습니다.
![image](https://user-images.githubusercontent.com/53327279/145025483-c37e67e3-3fb0-45f1-95dd-5474ceec3cc6.png)

https://github.com/Ind-Univ-Project/Food-Palette/blob/a8d374b6f2bbee7989595cba90be68dad2e652bb/front_end/MenuRecommendation.html

![image](https://user-images.githubusercontent.com/53327279/145025644-7b894f87-e469-4adb-b7b6-29b5b85debee.png)
https://github.com/Ind-Univ-Project/Food-Palette/blob/a8d374b6f2bbee7989595cba90be68dad2e652bb/front_end/MenuRecommendation18.html

**Comment by DA-EUN00** [comment]
색에 대해서 코멘트 주세요. 
구성이라든가 개수라든가 아무거나요.

**Comment by hhs629629** [comment]
개수 자체는 보면서 조절하는게 적절하다고 생각하니 맡기겠습니다
구성은 초록이나 빨강이 조금 많이 포함되면 좋을 것 같네요
아무래도 음식 구성이 그쪽 색이 많으니

**Comment by DA-EUN00** [comment]
일단 선택지가 작은 경우에는 8개 영역의 중간값을 나타낸 것이고, 
선택지가 많은 경우에는 8개 영역의 중간 값에 빨간색과 초록색의 영역을 추가한 것입니다.
일단 2개의 색 선택 화면을 제공한다고 한다면 현재의 구성이 나쁘지 않은 것 같습니다.
