### ISSUE TITLE
My Page부분 기능

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#59]
![image](https://user-images.githubusercontent.com/53327279/145225877-e06f44a4-3dcc-4907-bfbb-fcb0013b4994.png)
![image](https://user-images.githubusercontent.com/53327279/145225967-cf1633fe-7592-4897-8c77-2aea1f7a05b1.png)

MyPage의 화면 부분입니다. 
크게 사용자 정보 보여주는 부분과 과거 기록을 보여주는 부분으로 이뤄집니다.

**Comment by DA-EUN00** [comment]
My Page API부분은 어떻게 되나요?

**Comment by hhs629629** [comment]
MyPage영역은 프론트에서 구현하시면 될 것 같아요
별도의 API콜은 없습니다

**Comment by DA-EUN00** [comment]
네 알겠습니다.
