### ISSUE TITLE
colors POST 400 오류

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#61]
Bad Request가 뜨는데 왜 그러시는 지 아시나요?

https://github.com/Ind-Univ-Project/Food-Palette/blob/cba245dac2a0a1b4a829dfeab8fa943ebdaf5c29/front_end/MenuRecommendation.html

해당 부분 실행시 발생했어요.

관련 js는 
![image](https://user-images.githubusercontent.com/53327279/145236903-3e203859-07b6-4c10-8d11-21673f6aaae9.png)
입니다.

**Comment by hhs629629** [comment]
colorHexList랑 foodList가  Empty List인것 같네요

**Comment by DA-EUN00** [comment]
알려주신부분을 수정하니 오류가 해결되었습니다. 감사합니다!!!
