### ISSUE TITLE
최종발표_개발된 UI 상황

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#66]
개발된 UI 상홯입니다.
해당 동영상은 최종발표 때도 사용할 예정입니다.
의견 주세요.

1. main, sign up, log in, my page
https://youtu.be/YtcRdQfgm-o

2. 메뉴 추천
https://youtu.be/72elcAU3Dm8

3. index 화면
https://youtu.be/oHYZ37JsuUs

원본동영상은 파일이 너무 커서 압축파일로 올려요.
[UI.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7689952/UI.zip)

**Comment by hhs629629** [comment]
저희가 원하는 바가 잘 표현 되어 있는 것 같네요
