### ISSUE TITLE
첫번째 발표 자료

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#7]
지금까지 나온 아이디어를 정리해서 발표 자료를 만들었습니다.
확인해보시고 문제가 있다면 알려주세요. 
[1st 발표자료.pptx](https://github.com/Ind-Univ-Project/Food-Palette/files/7145484/1st.pptx)

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/132940054-2509bbea-275f-443c-8360-9cc32ac4ada9.png)
이 부분을 어떤 느낌으로 발표하길 원해서 넣은건지 잘 짐작이 안가네요

![image](https://user-images.githubusercontent.com/4403080/132940219-45fae295-ec20-4fb3-a5c0-ee781de5ea98.png)
그리고 이부분은 성별/나이의 음식과의 관련성을 입증할 데이터가 없으면 구현이 힘들수도 있을것 같은데
관련 데이터를 혹시 갖고있는게 있을까요

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/132940728-999a37a5-c41f-48c8-9aab-5210150f0d48.png)

- 문제
에서 Input, Output 을 별도로 구성 해주는게 적절할 것 같습니다

**Comment by DA-EUN00** [comment]
1. 매운 음식을 먹고 싶어!
우리가 흔히 '오늘은 매콤하고 시원한걸 먹고 싶어'라든지, '상큼한 채소를 먹고 싶어'라고 하죠. 첫번째 예시의 경우에는 해물탕, 찌개, 매운 라면이나 짬뽕이 될 수 있는데, 메뉴에는 맛으로 선택할 수 가 없다는 거죠. 그래서 넣었습니다. 
2. 연관성이 있다고 보통 생각하기 때문에 조사를 안했고, 따라서 관련 데이터는 없습니다. 
3. input,output은 추가 해서 올리겠습니다.

**Comment by DA-EUN00** [comment]
수정한 자료 입니다.
[1st 발표자료.pptx](https://github.com/Ind-Univ-Project/Food-Palette/files/7147889/1st.pptx)

**Comment by DA-EUN00** [comment]
아니면 선호 음식을 선택할 수 있는 그룹을 만들고 선택하게 할까요?
예를 들면 말이죠.
선호하는 지역 음식이라든지, 최근 며칠동안 먹은 음식을 표시한다든지, 아니면 단순히 그룹을 만들고 그룹을 대표하는 몇가지 음식을 좋아하는지 여부만 표시하도록 하는거죠.

**Comment by hhs629629** [comment]
그룹으로 묶는다는거 자체는 연산하는 입장에선 좋을 수 있으나
그룹의 적정선을 찾기 아주 힘들것 같네요

연관성을 연산해줄 데이터가 없다면 내용에서 빼는게 좋을것 같습니다

그리고 배경색이 밝은 계열인데 글자도 밝아서 조금 가시성이 떨어지는것 같네요

**Comment by hhs629629** [comment]
알고리즘 쪽의 설명을 도와줄 그림이 하나정도 있어도 괜찮을 것 같아 개략적인 구조도를 하나 그려봤습니다
![3th_week](https://user-images.githubusercontent.com/4403080/132955785-da316ec0-dbde-4392-805e-a772309779da.png)

**Comment by DA-EUN00** [comment]
2번째 수정 자료입니다.
input 부분에서 나이와 성별을 뺐습니다.
[1st 발표자료.pptx](https://github.com/Ind-Univ-Project/Food-Palette/files/7149025/1st.pptx)

**Comment by bytecell** [comment]
정영섭Prof: 좋습니다. ^^
