### ISSUE TITLE
입력으로 받을 색의 다양성 및 횟수 선정

### ISSUE THREAD

**Issue by hhs629629** [Ind-Univ-Project/Food-Palette#8]
사용자에게 입력 받을 색은 기본적으로 R G B 각 256개의 경우의 수로 16777216 가지가 되므로
사용자가 색을 쉽게 선택하기도 어렵고, 좋은 결과를 출력해주는데도 상당히 방해가 됩니다.

또한 사용자가 단 하나의 색만을 선택할 경우 결과가 상당히 단순해질 수 있습니다.

이를 위해 전체 색을 몇가지 색으로 구분하여 입력/추천을 진행할지
그리고 사용자에게 총 몇개의 색을 입력 받을지 결정해야 합니다.

**Comment by hhs629629** [comment]
해당 사항의 결정은
데이터셋을 분석하여 정리할 DB에도 큰 영향을 미치며
사용자에게 제공할 UI를 구성하는데도 중요한 요소이기 때문에
본격적인 개발이 시작되기 전에 결정해야 합니다.

**Comment by DA-EUN00** [comment]
일단 관련 논문을 조사해서 색과 음식 선택의 연관성을 정리하고 다시 의논하는 게 좋을 것 같습니다.
조사를 해서 정리하는 데로 올리겠습니다.

**Comment by DA-EUN00** [comment]
감정과 음식 선택을 연구한 논문을 바탕으로 감정은 
기쁨, 슬픔, 즐거움, 분노, 편안함, 우울
로 나누었습니다.

감정은 
빨강, 노랑, 초록, 파랑, 보라색, 흰색, 검정색
으로 크게 나눌 수 있습니다. 

하지만 음식의 맛이나 색을 표현하기에는 적다고 생각하여
빨강, 주황, 노랑, 초록, 파랑, 보라, 흰색, 검정, 갈색, 분홍
으로 하는 것은 어떤가요?

**Comment by DA-EUN00** [comment]
추가적으로 색도 그 밝기에 따라 다양한 감정을 나타낼 수 있습니다.
https://tecin.tistory.com/60

한국음식과 감정의 상관관계를 나타낸 논문을 큰 틀로 잡고 진행을 하면 좋을 듯합니다.
https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE10077014

**Comment by hhs629629** [comment]
색과 심리의 연관성은 관련 자료를 준비해서 차후 프레젠테이션에 반영하면 될것 같네요

색의 구분은 빨주노초파남보흰검갈분 으로 나눈다음에 색 전체에 대해서 영역을 정해야 합니다
가령 분홍은 FFC0CB의 값을 가지고 빨강은 FF0000의 값을
가진다고 가정합니다
그러면 음식 사진을 분석할때 어떤 픽셀이
FF66BB로 나온다면 이걸 분홍으로 봐야할지 빨강으로 봐야할지 경계를 정해야 합니다

즉 저희는 RGB로 구성될 수 있는 모든 색 영역을
몇분할 할지를 결정해야 합니다 그리고 또한 그 기준을 정해야 합니다

분류할 색이 너무 경우의 수가 적으면 유저가 선택의 다양성이 떨어져서 정확도나 재미가 떨어질 수 있고
너무 가짓수가 많아지면 DB용량이나 실행효율이 떨어질겁니다

**Comment by bytecell** [comment]
Prof: Issue 를 잘 작성하고 있네요.
Cafe 에서 언급했던것처럼,
각자 프로그램 개발에서 맡은 부분을 따로 issue로 파서 글을 작성해도 됩니다.

**Comment by hhs629629** [comment]
데이터를 RGB24 정도로 잡을 때
R, G, B 각 0~255의 값을 가지므로
각 색별로 4등분을 하여서
총 4³ = 64색을 제공하는게 어떨까요?
