### ISSUE TITLE
요구사항 정의서 

### ISSUE THREAD

**Issue by DA-EUN00** [Ind-Univ-Project/Food-Palette#9]

**Comment by DA-EUN00** [comment]
요구사항 정의서를 작성해봤습니다.
확인부탁드려요.
참고로 요구사항 분석서는 다이어그램 때문에 시간이 좀 걸릴 것 같습니다.

[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7241192/6-.zip)
한글 파일은 지원을 안해서 압축파일로 올립니다.

**Comment by hhs629629** [comment]
주요 기능에 있어서 사용자에게 입력 받을 색을 10개로 설정했는데
10개랑 음식을 연결한다고 하면 색 당 4개의 음식을 할당해도
40개의 음식 종류밖에 추천을 하지 못하는데
색을 10개로 한정하는게 맞는지 검토해볼 필요가 있을 것 같네요

**Comment by DA-EUN00** [comment]
일단 색의 종류랑 개수에 대해 논의 중이라서 10개로 적었습니다.
말씀하신대로 개수가 너무 적으면 음식을 추천할 수 있는 종류가 적고,
개수가 너무 많으면 사용자의 혼동을 초래할 수 있을 것 같습니다. 

이 부분이 멘토링을 통해 해결할 수 있으면 좋겠네요.

**Comment by hhs629629** [comment]
기능적 요구사항에
감정 분석 기능과 음식 추천 기능을 나눴는데
해당 구조로 프로그램을 만들 시
감정과 음식을 직관적으로 연결해줄 로직을 찾아내야 합니다.
그런 로직 또는 검증해줄 데이터가 충분히 없다면 해당 기능은 구현을 실패할 확률이 높을 것 같네요

또한 색깔 기준으로 감정을 분석한다고 보기에는
그냥 빨간색이 마음에 들어서 선택했는데 분노의 감정으로 분석되는 등
정확성 측면에서 문제가 생길 수 있습니다.

**Comment by hhs629629** [comment]
운영 환경에 대한 요구사항의 

> OR1. 시스템은 안드로이드 운영체제에서 동작해야 한다

와
내부 시스템 인터페이스 요구사항의 

> IIF1. 시스템은 모든 기능을 터치 인터페이스를 이용하여 사용할 수 있어야 한다.

는

웹으로 제공될 시스템인게 프로젝트 정의에서 기재되어 있기 때문에
안드로이드 환경에서도 웹 브라우저를 통해 당연히 접속할 수 있고
안드로이드가 아니더라도 iOS, MacOS, Linux 등의 환경도 웹 브라우저가 있으면 접속이 가능하기 때문에

> 웹 브라우저를 사용할 수 있는 모든 환경에서 동작해야 한다

또는
> 웹 브라우저에서 동작해야 한다

가 더 넓은 범위를 커버하는 것 같아서 좋을 것 같아요

그리고 일반적으로 모바일 장치의 웹브라우저에서 터치는 클릭과 동일하기 때문에
터치를 위한 별도 지원이 저희 서비스에서 제공될 필요는 없습니다.

그렇지만 다양한 환경에서 접근 가능한 만큼
다양한 크기의 화면에서 적절한 UI/UX를 제공할 필요는 있을것 같네요

**Comment by hhs629629** [comment]
음식 추천 시스템 이용 관련 기능에

> FF1.1.1. 사용자는 회원가입 시 정보(아이디, 비밀번호, 이름, 지역 등)를 입력해야 한다.
FF1.3.1. 사용자는 ‘지역’을 변경할 수 있다. 

등 지역 관련 내용이 있는데
지역을 음식을 추천하는데 사용할 수 없다면 수집할 필요가 없다고 생각합니다


> 3-3) 보안 요구사항 - SR
SR1. 시스템은 회원의 정보(이름, 휴대폰 번호 등)를 수집한다.
SR2. 회원의 개인정보는 암호화한다.

여기서 휴대폰 번호의 수집하는 이유가 무엇인가요?

**Comment by DA-EUN00** [comment]
일단 우리가 색을 선택해서 추천을 해주니까 어떤 걸 기준으로 해야할지를 명확히 정할 필요가 있습니다. 
저도 의견 주신 내용으로 고민을 하고 있었거든요. 명확한 데이터를 찾는 게 필요할 것 같습니다.

의견 주신 내용을 반영해서 수정하겠습니다.

3-3) 보안 요구사항 - SR
질문주신 이 부분은 실수로 들어간 것 같습니다. 내용을 빼도록 하겠습니다.

**Comment by DA-EUN00** [comment]
[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7253150/6-.zip)
의견주신대로 변경했습니다.
지역 음식을 넣으려고 '지역'항목을 추가했었는데, 큰 영향이 없을 것 같아서 뺐습니다.

**Comment by DA-EUN00** [comment]
의견주신대로 변경했습니다.
지역 음식을 넣으려고 '지역'항목을 추가했었는데, 큰 영향이 없을 것 같아서 뺐습니다.
[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7253626/6-.zip)

**Comment by DA-EUN00** [comment]
멘토링받은 의견을 추가해서 수정했습니다.
멘토링 당시 기존 선택을 저장하라고 하셨는데, 문서를 다시보니 2-2) 사용자 데이터 분석 기능 - UF1에 해당내용이 있음을 확인했습니다
[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7275706/6-.zip)
.

**Comment by hhs629629** [comment]
주요 기능 설명란의 사용자의 감정 분석기능을 구현할 방법이 있을까요?

**Comment by hhs629629** [comment]
FF1.3.2. 와 FF3.1.1. 의 내용이 겹치는것 같은데 두번 작성된 이유가 있나요?

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/135808891-98391011-cc3e-47d7-864a-cc4edf6c02fe.png)

사용자 데이터 분석 기능에서 "수집한 데이터를 통해 시스템을 보강한다"라고 되어 있는데
어떤 데이터를 통해 어떤 시스템을 보강할지 계획 되어있는게 있나요?

**Comment by DA-EUN00** [comment]
감정분석의 경우 처음부터 사용자에게 자시느이 감정을 나타낼 수 있는 색을 골라달라고 말하고, 이 색들이 어떤 감정과 연관이 있는지 알아내면 됩니다. 색과 감정의 상관관계는 색채심리학 논문을 찾아보고 있습니다. 
![348c218fce7640a59fcb425164caf2ab](https://user-images.githubusercontent.com/53327279/135809378-9de8b5fa-285b-4790-bf8b-50493ce59e8c.jpg)
아마도 이런 자료를 이용하지 않을까 싶습니다.


FF1.3.2. 와 FF3.1.1.는 같은 내용이지만 사용자의 '마이페이지'에서 확인할 수 있다는 점을 알리고 싶어서 2번 넣었습니다.

UF3의 경우는 사용자에게 입력받은 음식의 사진과 평가를 시스템에 보강한다는 의미입니다.
음식의 사진은 사진 데이터에 추가할 것이고,
입력받은 평가는 사용자에게 추천되는 메뉴에 반영할 생각입니다.
제 생각에 제가 추어탕을 안먹는데 추천 메뉴에 매번 추어탕이 올라온다면 해당 서비스를 사용하는데 불편이 있을 것 같아서요.


[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7276189/6-.zip)
숫자를 바꾸지 않은 부분이 있어서 수정하여 올립니다.

**Comment by hhs629629** [comment]
사용자의 감정 분석의 자료 활용 자체는 문제가 없습니다
그런데 문제는 사용자의 감정 분석 결과와
사용자에게 추천하는 음식이 매끄럽게 이어지려면

A라는 감정일 때 B라는 음식을 선택한다
라는 데이터를 얻어야 하는데 현재로썬 그럴 데이터가 없습니다
그래서 음식 사진에 포함된 픽셀의 색 데이터를 통해서 추천하려는 계획인데

"감정" 기반으로 추천을 진행하려면 적절한 데이터를 얻거나, 로직을 만들 필요가 있을것 같습니다

사용자에게 색 입력 받음 -> 감정 분석 -> 감정을 통한 음식 추천 보단
사용자에게 색 입력 받음 -> 색을 통한 음식 추천이

데이터나 로직이 없을 경우 구현에 있어서 더 적절하다고 생각합니다

**Comment by hhs629629** [comment]
사용자가 먹지 않는 음식은 추천을 해준 다음에 평가를 통해 제거하기보단
마이페이지에서 먹는 음식 그룹을 설정할 수 있도록 하는게 적절해 보입니다

**Comment by DA-EUN00** [comment]
'A라는 감정일 때 B라는 음식을 선택한다'라는 것은 참고문헌 파일의 4쪽을 이용하면 어떨까합니다.

먹는 음식 그룹을 설정한다는게 잘 이해가 되지 않는데 추가설명 부탁드려요.

**Comment by hhs629629** [comment]
4쪽을 이용한다 하더라도 여전히 문제가 있습니다

첫째로 참고 문헌에 의해 개발하면 총 6종류의 감정밖에 제공하지 못합니다
이 때 멘토링에서 받은 기존에 나왔던 선택은 가급적 다음에 안나오게 해야 좋을 것 같다는 점을 고려해보면
사용자는 5개정도의 선택지밖에 없을 겁니다
UI/UX가 특히 중점인 저희 서비스에서 선택지가 5개인 경우는 UX가 좋게 나오기 힘들것 같네요

둘째로 음식을 분류하는게 매우 어려울겁니다
저희는 현재 저희가 넣은 음식 사진 외에도 멘토링을 통해 추가한 유저가 사진을 업로드 하는 기능을 채용했는데요
유저가 사진을 업로드 할 때 "만두" 를 올렸다고 가정 합니다
참고 문헌 상으로는 "분식" 에 가까운 것이겠지만 "만두" 를 "분식" 에 대응해줄 로직을 저희는 갖고있지 않습니다

셋째로 해당 참고 문헌이 대응시켜주지 못하거나 너무 뭉뚱그린 항목들이 있습니다
매운 음식을 분노의 감정을 가질때만 먹게 하는것은 한국 정서상 그다지 공감받지 못할 내용일 것 같고요
해당 논문의 분류가 뭉뚱그려진점으로는 구이류와 스테이크가 동시에 존재하는데
앞으로 계속 음식을 추가하더라도 이 애매한 카테고리 안에서 추가해 나갈 수 있을지는 의문입니다

유저의 감정을 분석해주는 부분도 막상 사용할 경우를 생각하면 애매한것 같네요
감정을 결국 음식과 대응하려면 감정을 6개로 정리해야 하는데
대부분 실제 유저의 감정과는 거리가 있는 결과를 출력해줄 것 같습니다

**Comment by DA-EUN00** [comment]
그럼 저희는 감정은 빼고 선택한 색상이 들어가는 음식을 추천해주는 추천 시스템인거죠?
마이페이지에서 안먹는 그룹군을 설정하도록 수정하겠습니다.

**Comment by DA-EUN00** [comment]
[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7277903/6-.zip)

의견주신대로 수정했습니다.

**Comment by hhs629629** [comment]
감정 영역은 저희의 시스템의 개연성으로는 활용 하되
메인 로직을 논문에 근거해서 짜면 난이도가 어려워질 것 같아요

**Comment by DA-EUN00** [comment]
[6-요구사항정의서.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7326533/6-.zip)
일부 사항을 수정했습니다.

**Comment by hhs629629** [comment]
![image](https://user-images.githubusercontent.com/4403080/137103451-eb7bc06a-967f-4c38-bc57-21b33cfa8d3d.png)
재개정 이력에 해당 수정사항이 반영되지 않았습니다
![image](https://user-images.githubusercontent.com/4403080/137103517-0fd4b213-4849-47bc-8f43-53a69f06e3fb.png)
'집합' 오타 있습니다

**Comment by DA-EUN00** [comment]
코멘트 주신 부분 수정했습니다.
[요구사항정의서_빌더.zip](https://github.com/Ind-Univ-Project/Food-Palette/files/7339316/_.zip)
